// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: stripe/v1/stripe_service.proto

package stripev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CancelSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_stripe_v1_stripe_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stripe_v1_stripe_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_stripe_v1_stripe_service_proto_rawDescGZIP(), []int{0}
}

func (x *CancelSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type CancelSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionResponse) Reset() {
	*x = CancelSubscriptionResponse{}
	mi := &file_stripe_v1_stripe_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionResponse) ProtoMessage() {}

func (x *CancelSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stripe_v1_stripe_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_stripe_v1_stripe_service_proto_rawDescGZIP(), []int{1}
}

type VerifySubscriptionValidityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserExternalId string                 `protobuf:"bytes,1,opt,name=user_external_id,json=userExternalId,proto3" json:"user_external_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifySubscriptionValidityRequest) Reset() {
	*x = VerifySubscriptionValidityRequest{}
	mi := &file_stripe_v1_stripe_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySubscriptionValidityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySubscriptionValidityRequest) ProtoMessage() {}

func (x *VerifySubscriptionValidityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stripe_v1_stripe_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySubscriptionValidityRequest.ProtoReflect.Descriptor instead.
func (*VerifySubscriptionValidityRequest) Descriptor() ([]byte, []int) {
	return file_stripe_v1_stripe_service_proto_rawDescGZIP(), []int{2}
}

func (x *VerifySubscriptionValidityRequest) GetUserExternalId() string {
	if x != nil {
		return x.UserExternalId
	}
	return ""
}

type VerifySubscriptionValidityResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IsValidSubscription bool                   `protobuf:"varint,1,opt,name=is_valid_subscription,json=isValidSubscription,proto3" json:"is_valid_subscription,omitempty"`
	InvalidityType      string                 `protobuf:"bytes,2,opt,name=invalidity_type,json=invalidityType,proto3" json:"invalidity_type,omitempty"`
	ValidityType        string                 `protobuf:"bytes,3,opt,name=validity_type,json=validityType,proto3" json:"validity_type,omitempty"`
	StripeCustomerEmail string                 `protobuf:"bytes,4,opt,name=stripe_customer_email,json=stripeCustomerEmail,proto3" json:"stripe_customer_email,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VerifySubscriptionValidityResponse) Reset() {
	*x = VerifySubscriptionValidityResponse{}
	mi := &file_stripe_v1_stripe_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySubscriptionValidityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySubscriptionValidityResponse) ProtoMessage() {}

func (x *VerifySubscriptionValidityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stripe_v1_stripe_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySubscriptionValidityResponse.ProtoReflect.Descriptor instead.
func (*VerifySubscriptionValidityResponse) Descriptor() ([]byte, []int) {
	return file_stripe_v1_stripe_service_proto_rawDescGZIP(), []int{3}
}

func (x *VerifySubscriptionValidityResponse) GetIsValidSubscription() bool {
	if x != nil {
		return x.IsValidSubscription
	}
	return false
}

func (x *VerifySubscriptionValidityResponse) GetInvalidityType() string {
	if x != nil {
		return x.InvalidityType
	}
	return ""
}

func (x *VerifySubscriptionValidityResponse) GetValidityType() string {
	if x != nil {
		return x.ValidityType
	}
	return ""
}

func (x *VerifySubscriptionValidityResponse) GetStripeCustomerEmail() string {
	if x != nil {
		return x.StripeCustomerEmail
	}
	return ""
}

// SpendingUnit represents a unit to insert.
type SpendingUnit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExternalId     string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	UserExternalId string                 `protobuf:"bytes,2,opt,name=user_external_id,json=userExternalId,proto3" json:"user_external_id,omitempty"`
	Amount         int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix ms
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpendingUnit) Reset() {
	*x = SpendingUnit{}
	mi := &file_stripe_v1_stripe_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendingUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendingUnit) ProtoMessage() {}

func (x *SpendingUnit) ProtoReflect() protoreflect.Message {
	mi := &file_stripe_v1_stripe_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendingUnit.ProtoReflect.Descriptor instead.
func (*SpendingUnit) Descriptor() ([]byte, []int) {
	return file_stripe_v1_stripe_service_proto_rawDescGZIP(), []int{4}
}

func (x *SpendingUnit) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *SpendingUnit) GetUserExternalId() string {
	if x != nil {
		return x.UserExternalId
	}
	return ""
}

func (x *SpendingUnit) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SpendingUnit) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type AddSpendingUnitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SpendingUnit        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSpendingUnitsRequest) Reset() {
	*x = AddSpendingUnitsRequest{}
	mi := &file_stripe_v1_stripe_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSpendingUnitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSpendingUnitsRequest) ProtoMessage() {}

func (x *AddSpendingUnitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stripe_v1_stripe_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSpendingUnitsRequest.ProtoReflect.Descriptor instead.
func (*AddSpendingUnitsRequest) Descriptor() ([]byte, []int) {
	return file_stripe_v1_stripe_service_proto_rawDescGZIP(), []int{5}
}

func (x *AddSpendingUnitsRequest) GetItems() []*SpendingUnit {
	if x != nil {
		return x.Items
	}
	return nil
}

type AddSpendingUnitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      int32                  `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"` // number of rows inserted (duplicates skipped)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSpendingUnitsResponse) Reset() {
	*x = AddSpendingUnitsResponse{}
	mi := &file_stripe_v1_stripe_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSpendingUnitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSpendingUnitsResponse) ProtoMessage() {}

func (x *AddSpendingUnitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stripe_v1_stripe_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSpendingUnitsResponse.ProtoReflect.Descriptor instead.
func (*AddSpendingUnitsResponse) Descriptor() ([]byte, []int) {
	return file_stripe_v1_stripe_service_proto_rawDescGZIP(), []int{6}
}

func (x *AddSpendingUnitsResponse) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

var File_stripe_v1_stripe_service_proto protoreflect.FileDescriptor

const file_stripe_v1_stripe_service_proto_rawDesc = "" +
	"\n" +
	"\x1estripe/v1/stripe_service.proto\x12\tstripe.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/httpbody.proto\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\x19CancelSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"\x1c\n" +
	"\x1aCancelSubscriptionResponse\"M\n" +
	"!VerifySubscriptionValidityRequest\x12(\n" +
	"\x10user_external_id\x18\x01 \x01(\tR\x0euserExternalId\"\xda\x01\n" +
	"\"VerifySubscriptionValidityResponse\x122\n" +
	"\x15is_valid_subscription\x18\x01 \x01(\bR\x13isValidSubscription\x12'\n" +
	"\x0finvalidity_type\x18\x02 \x01(\tR\x0einvalidityType\x12#\n" +
	"\rvalidity_type\x18\x03 \x01(\tR\fvalidityType\x122\n" +
	"\x15stripe_customer_email\x18\x04 \x01(\tR\x13stripeCustomerEmail\"\x90\x01\n" +
	"\fSpendingUnit\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12(\n" +
	"\x10user_external_id\x18\x02 \x01(\tR\x0euserExternalId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"H\n" +
	"\x17AddSpendingUnitsRequest\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.stripe.v1.SpendingUnitR\x05items\"6\n" +
	"\x18AddSpendingUnitsResponse\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\x05R\binserted2\xa6\x04\n" +
	"\rStripeService\x12\x86\x01\n" +
	"\x12CancelSubscription\x12$.stripe.v1.CancelSubscriptionRequest\x1a%.stripe.v1.CancelSubscriptionResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/cancel-subscription\x12\xa7\x01\n" +
	"\x1aVerifySubscriptionValidity\x12,.stripe.v1.VerifySubscriptionValidityRequest\x1a-.stripe.v1.VerifySubscriptionValidityResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/verify-subscription-validity\x12e\n" +
	"\rHandleWebhook\x12\x14.google.api.HttpBody\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/receive-stripe-webhook\x12{\n" +
	"\x10AddSpendingUnits\x12\".stripe.v1.AddSpendingUnitsRequest\x1a#.stripe.v1.AddSpendingUnitsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/spending-unitsBXZVgithub.com/tbeaudouin05/stripe-trellai/internal/autogenerated/proto/stripe/v1;stripev1b\x06proto3"

var (
	file_stripe_v1_stripe_service_proto_rawDescOnce sync.Once
	file_stripe_v1_stripe_service_proto_rawDescData []byte
)

func file_stripe_v1_stripe_service_proto_rawDescGZIP() []byte {
	file_stripe_v1_stripe_service_proto_rawDescOnce.Do(func() {
		file_stripe_v1_stripe_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stripe_v1_stripe_service_proto_rawDesc), len(file_stripe_v1_stripe_service_proto_rawDesc)))
	})
	return file_stripe_v1_stripe_service_proto_rawDescData
}

var file_stripe_v1_stripe_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_stripe_v1_stripe_service_proto_goTypes = []any{
	(*CancelSubscriptionRequest)(nil),          // 0: stripe.v1.CancelSubscriptionRequest
	(*CancelSubscriptionResponse)(nil),         // 1: stripe.v1.CancelSubscriptionResponse
	(*VerifySubscriptionValidityRequest)(nil),  // 2: stripe.v1.VerifySubscriptionValidityRequest
	(*VerifySubscriptionValidityResponse)(nil), // 3: stripe.v1.VerifySubscriptionValidityResponse
	(*SpendingUnit)(nil),                       // 4: stripe.v1.SpendingUnit
	(*AddSpendingUnitsRequest)(nil),            // 5: stripe.v1.AddSpendingUnitsRequest
	(*AddSpendingUnitsResponse)(nil),           // 6: stripe.v1.AddSpendingUnitsResponse
	(*httpbody.HttpBody)(nil),                  // 7: google.api.HttpBody
	(*emptypb.Empty)(nil),                      // 8: google.protobuf.Empty
}
var file_stripe_v1_stripe_service_proto_depIdxs = []int32{
	4, // 0: stripe.v1.AddSpendingUnitsRequest.items:type_name -> stripe.v1.SpendingUnit
	0, // 1: stripe.v1.StripeService.CancelSubscription:input_type -> stripe.v1.CancelSubscriptionRequest
	2, // 2: stripe.v1.StripeService.VerifySubscriptionValidity:input_type -> stripe.v1.VerifySubscriptionValidityRequest
	7, // 3: stripe.v1.StripeService.HandleWebhook:input_type -> google.api.HttpBody
	5, // 4: stripe.v1.StripeService.AddSpendingUnits:input_type -> stripe.v1.AddSpendingUnitsRequest
	1, // 5: stripe.v1.StripeService.CancelSubscription:output_type -> stripe.v1.CancelSubscriptionResponse
	3, // 6: stripe.v1.StripeService.VerifySubscriptionValidity:output_type -> stripe.v1.VerifySubscriptionValidityResponse
	8, // 7: stripe.v1.StripeService.HandleWebhook:output_type -> google.protobuf.Empty
	6, // 8: stripe.v1.StripeService.AddSpendingUnits:output_type -> stripe.v1.AddSpendingUnitsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stripe_v1_stripe_service_proto_init() }
func file_stripe_v1_stripe_service_proto_init() {
	if File_stripe_v1_stripe_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stripe_v1_stripe_service_proto_rawDesc), len(file_stripe_v1_stripe_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stripe_v1_stripe_service_proto_goTypes,
		DependencyIndexes: file_stripe_v1_stripe_service_proto_depIdxs,
		MessageInfos:      file_stripe_v1_stripe_service_proto_msgTypes,
	}.Build()
	File_stripe_v1_stripe_service_proto = out.File
	file_stripe_v1_stripe_service_proto_goTypes = nil
	file_stripe_v1_stripe_service_proto_depIdxs = nil
}
