// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqldb

import (
	"database/sql"
)

type FreeCredit struct {
	ID             int64  `json:"id"`
	UserExternalID string `json:"user_external_id"`
	Credit         int32  `json:"credit"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

type InvalidSubscription struct {
	ID                   int64          `json:"id"`
	UserExternalID       string         `json:"user_external_id"`
	StripeSubscriptionID sql.NullString `json:"stripe_subscription_id"`
	StripePlanID         sql.NullString `json:"stripe_plan_id"`
	StripeCustomerID     sql.NullString `json:"stripe_customer_id"`
	CreatedAt            int64          `json:"created_at"`
	UpdatedAt            int64          `json:"updated_at"`
}

type SpendingUnit struct {
	ID             int64  `json:"id"`
	ExternalID     string `json:"external_id"`
	UserExternalID string `json:"user_external_id"`
	Amount         int32  `json:"amount"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

type UserAccount struct {
	ID                   int64          `json:"id"`
	UserExternalID       string         `json:"user_external_id"`
	StripeSubscriptionID sql.NullString `json:"stripe_subscription_id"`
	StripePlanID         sql.NullString `json:"stripe_plan_id"`
	StripeCustomerID     sql.NullString `json:"stripe_customer_id"`
	CreatedAt            int64          `json:"created_at"`
	UpdatedAt            int64          `json:"updated_at"`
}
