// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqldb

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountUnitsBetween(ctx context.Context, arg CountUnitsBetweenParams) (interface{}, error)
	GetSubscriptionIDByUserExternalID(ctx context.Context, userExternalID string) (sql.NullString, error)
	GetUserAccount(ctx context.Context, userExternalID string) (GetUserAccountRow, error)
	InsertInvalidSubscription(ctx context.Context, arg InsertInvalidSubscriptionParams) error
	InsertSpendingUnit(ctx context.Context, arg InsertSpendingUnitParams) (interface{}, error)
	UpsertAndGetFreeCredit(ctx context.Context, arg UpsertAndGetFreeCreditParams) (int32, error)
	UpsertUserAccount(ctx context.Context, arg UpsertUserAccountParams) error
}

var _ Querier = (*Queries)(nil)
